language: ruby
cache: bundler
before_install:
  - gem install bundler
  - gem update bundler
install:
  - bundle install
before_script:
  - bundle update
rvm:
  - 2.5
  - 2.4
  - 2.2
  - jruby-9.2.0.0
jobs:
  include:
    - stage: Lint
      rvm: 2.5
      before_install:
        - gem install rubocop
      script: rubocop
notifications:
  email: false
