name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        entry:
          - ruby: '2.7'
          - ruby: '3.0'
          - ruby: '3.1'
    name: ruby ${{ matrix.entry.ruby }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.entry.ruby }}
      - run: bundle install --jobs=3 --retry=3
      - run: bundle exec rake
